# Generated by Django 5.2.6 on 2025-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
