# Generated by Django 5.2.6 on 2025-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empleado_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
